# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: 'stock_analytics'
version: '1.0.0'

# This setting configures which "profile" dbt uses for this project.
profile: 'stock_analytics'


model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"


# Configuring models
models:
  stock_analytics:
    # Config for all models in the project
    +persist_docs:
      relation: true
      columns: true
    
    # Staging models
    staging:
      +materialized: view
      +schema: raw
      +tags: ['staging']
    
    # Intermediate models
    intermediate:
      +materialized: table
      +schema: analytics
      +tags: ['intermediate', 'technical_indicators']
    
    # Marts models
    marts:
      +materialized: table
      +schema: analytics
      +tags: ['marts', 'business_metrics']

# Snapshot configuration
snapshots:
  stock_analytics:
    +target_schema: analytics
    +strategy: check
    +unique_key: snapshot_key
    +tags: ['snapshot']
  
# Test configurations
tests:
  stock_analytics:
    +store_failures: true
    +schema: test_failures