version: 2

models:
  - name: stg_stock_daily
    description: "Cleaned and validated daily stock prices"

    tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns:
            - SYMBOL
            - DATE
    
    columns:
      - name: SYMBOL
        description: "Stock ticker symbol"
        tests:
          - not_null
      
      - name: DATE
        description: "Trading date"
        tests:
          - not_null
      
      - name: CLOSE
        description: "Closing price"
        tests:
          - not_null
      
      - name: DATA_QUALITY_FLAG
        description: "Data quality validation flag"
        tests:
          - not_null
          - accepted_values:
              values: ['VALID', 'INVALID', 'ANOMALY', 'MISSING', 'NO_TRADING']
      
      - name: DAILY_CHANGE_PCT
        description: "Percentage change from open to close"
        tests:
          - not_null